"""Add forum models (Category, Thread, Post)

Revision ID: 2cea37c3bdff
Revises: 0a3acad3d50a
Create Date: 2025-04-19 17:53:44.757943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cea37c3bdff'
down_revision = '0a3acad3d50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('forum_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_category_slug'), ['slug'], unique=True)

    op.create_table('forum_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_post_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['forum_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_thread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_thread_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_thread_last_post_at'), ['last_post_at'], unique=False)

    op.create_table('forum_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_post_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_post_created_at'))

    op.drop_table('forum_post')
    with op.batch_alter_table('forum_thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_thread_last_post_at'))
        batch_op.drop_index(batch_op.f('ix_forum_thread_created_at'))

    op.drop_table('forum_thread')
    with op.batch_alter_table('forum_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_category_slug'))

    op.drop_table('forum_category')
    # ### end Alembic commands ###
