"""Add WikiPage model

Revision ID: ec91920f30ee
Revises: f437fc0d5897
Create Date: 2025-04-19 16:28:43.811806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec91920f30ee'
down_revision = 'f437fc0d5897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_slug'))

    op.drop_table('wiki_page')
    # ### end Alembic commands ###
