"""Add last post tracking to ForumThread

Revision ID: f31b6895ac72
Revises: 2cea37c3bdff
Create Date: 2025-04-19 21:51:15.037615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31b6895ac72'
down_revision = '2cea37c3bdff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_thread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_forum_thread_last_post_id_forum_post', 'forum_post', ['last_post_id'], ['id'])
        batch_op.create_foreign_key('fk_forum_thread_last_poster_id_user', 'user', ['last_poster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_thread', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_poster_id')
        batch_op.drop_column('last_post_id')

    # ### end Alembic commands ###
